core_values:
  - title: "Integrity"
    body: "Embrace honesty as the cornerstone of wisdom. Living a life of integrity not only enriches your own character but also earns the respect of those around you. When we act in alignment with our core values, we serve as role models for others, reinforcing a cycle of trust and accountability."
    quote: "Knowledge will give you power, but character respect."
    author: "Bruce Lee"
  - title: "Stewardship"
    body: 'The principle of "Rising tides raise all ships" encapsulates our approach to stewardship. We believe in nurturing and taking care of our community and environment as if it were a legacy we leave for future generations. By planting the seeds today for a better tomorrow, we embody leadership that is both compassionate and far-sighted.'
    quote: "A society grows great when old men plant trees whose shade they know they shall never sit in."
    author: "Greek Proverb"
  - title: "Trust"
    body: "Invest in trust to fortify all your relationships. Whether in personal connections or professional dealings, trust serves as the binding glue. It's more than just a word; it's a foundational principle that enhances communication and teamwork, enabling us to accomplish great things together."
    quote: "The best way to find out if you can trust somebody is to trust them."
    author: "Ernest Hemingway"
  - title: "Kaizen"
    body: "The courage to continue fuels every journey to success. We embrace Kaizen, the philosophy of continuous improvement, understanding that neither success nor failure is final. It's the ongoing courage to grow and adapt that brings about meaningful change, achieved through a series of small, deliberate actions."
    quote: "Success is not final, failure is not fatal: It is the courage to continue that counts."
    author: "Winston Churchill"
  - title: "Give Back"
    body: "The power of generosity extends far beyond the individual. Giving back is not just an act but a commitment to fostering a cycle of kindness and support within our community. Whether through time, resources, or expertise, the act of giving back creates a ripple effect of positivity. It enriches our lives, provides opportunities for others, and strengthens the social fabric that connects us all."
    quote: "Service to others is the rent you pay for your room here on Earth."
    author: "Muhammad Ali"
